[project]
name = "extension"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hiroaki Ogasawara", email = "13391129+xhiroga@users.noreply.github.com" }
]
requires-python = ">=3.11"

dependencies = [
    "websockets>=15.0.1",
    "zeroconf>=0.146.3",
]

[dependency-groups]
dev = [
    "bpy>=4.4.0",
    "fake-bpy-module>=20250412",
    "numpy<2",
    "tomlkit>=0.13.2",
]
