schema_version = "1.0.0"

id = "mcp_senpai"
version = "1.0.0"
name = "MCP Senpai"
tagline = "Senpai (menter) in your use of Blender, using the MCP protocol"
maintainer = "Hiroaki Ogasawara <13391129+xhiroga@users.noreply.github.com>"
type = "add-on"

blender_version_min = "4.2.0"
license = [
  "UNLICENSED",
]
